spring:
  datasource:
    url: jdbc:mysql://db-pre-project-005.ctbzai9oohqp.ap-northeast-2.rds.amazonaws.com:13306/preproject005?createDatabaseIfNotExist=true&createTableIfNotExist=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: preproject005
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    aws:
      s3:
        bucket: dowajoyak.shop
      region:
        static: ap-northeast-2
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  key: sebmain00511234123412341234123412341234123412341234
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@main005.com

config:
  domain: https://www.dowajoyak.shop