spring:
  datasource:
    url: jdbc:mysql://db-pre-project-005.ctbzai9oohqp.ap-northeast-2.rds.amazonaws.com:13306/preproject005?createDatabaseIfNotExist=true&createTableIfNotExist=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: preproject005
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 595193810049-e18ivlshe0brsekk7sn43jl3nf6rrfdm.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: https://server.dowajoyak.shop/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            client-id: O3ZePEHnOfML8lYr8ct3
            client-secret: ETHo0GWydA
            redirect-uri: 'https://server.dowajoyak.shop/login/oauth2/code/naver'
            authorization-grant-type: authorization_code
            scope: nickname,email
            client-name: Naver
          kakao:
            clientId: 053b38eb84613c61491ce616974c4f08
            clientSecret: FPSZpKCWCU22Rgq24pzswlbM1srbDruE
            redirect-uri: https://server.dowajoyak.shop/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        pathmatch:
            matching-strategy: ant_path_matcher
  cloud:
    aws:
      s3:
        bucket: dowajoyak.shop
      region:
        static: ap-northeast-2
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

jwt:
  key: sebmain00511234123412341234123412341234123412341234
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@main005.com

config:
  domain: https://www.dowajoyak.shop
